version: '3.1'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass_mongodb
    volumes:
      - ./init_mongo/:/docker-entrypoint-initdb.d/:ro
  
  backend:
    build: .
    ports:
      - "80:80"
